import type { Metadata } from 'next'
import { Inter } from "next/font/google"
import './globals.css'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "700"]})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={cn("h-screen w-screen", inter.className)} >{children}</body>
    </html>
  )
}
